### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by skerry3000** [Relorer/HTMLToQPDF#2]
Hi, I love using this library so far!  Are there any plans to have a new release soon to include these changes for being able to use an IContainer instead of a PageDescriptor?

https://github.com/Relorer/HTMLToQPDF/commit/11d29c87cd34e89a5f3bfb4596565379a57cc7a1

**Comment by skerry3000** [comment]
@Relorer Any updates on this?

**Comment by Relorer** [comment]
@skerry3000  Sorry for the wait, I have published a new release that includes the latest changes. But I don't have time to continue working on this library yet.
I think in the future I will return to its development.

**Comment by skerry3000** [comment]
@Relorer great, thank you so much!  Let me know if there is any way I can contribute.
